servo-core/src/main/java/com/netflix/servo/jmx/JmxMonitorRegistry.java

The MBeanServer used in JmxMonitorRegistry is shared across the VM.
Calls to register will occur from different threads, and results in a
race, particularly as names can easily clash.
By synchronizing on the mBeanServer, we can ensure the guard works
without introducing a complicated loop of catching
InstanceNotFoundException or InstanceAlreadyExistsException.
See https://github.com/Netflix/feign/issues/182

Removes race condition in JmxMonitorRegistry.register

---

servo-core/src/main/java/com/netflix/servo/publish/JmxMetricPoller.java

Logging warning when mbean query doesn't match any mbeans

---

servo-core/src/main/java/com/netflix/servo/publish/JmxMetricPoller.java
servo-core/src/test/java/com/netflix/servo/publish/JmxMetricPollerTest.java

This class turns out to a very useful building block for doing JMX collection and with a few additions can be even more useful.
3 small enhancements to JmxMetricsPoller:
* Parses TablularData like it was CompositeData
* Option to not filter out non-numeric metrics (useful when making a "JMX Dump" like tool that isn't feeding a monitoring system)
* Ability to add default tags to every metric to help identify the source (without needing an Observer for each host since we already have to have a poller for every host)

Some extensions to JmxMetricsPoller

---

build.gradle

Internal platform is moving to guava 16. This doesn't
require any code changes on our side, just moving the
dependency to keep things consistent.

update to guava 16

---

build.gradle
servo-atlas/build.gradle
servo-atlas/src/jmh/java/com/netflix/servo/publish/atlas/ValidCharactersBench.java
servo-atlas/src/main/java/com/netflix/servo/publish/atlas/ValidCharacters.java
servo-atlas/src/test/java/com/netflix/servo/publish/atlas/ValidCharactersTest.java

Update ValidCharacters.toValidCharset to use a hand crafted version.
The new version is around 5x faster than the previous regex based version:
```
c.n.s.p.a.ValidCharactersBench.testNewByHand     thrpt       50  4258892.253 ± 57887.069  ops/s
c.n.s.p.a.ValidCharactersBench.testUsingRegex    thrpt       50   923106.236 ±  8753.248  ops/s
```

Replace regex replaceAll with hand crafted version

---

servo-apache/src/main/java/com/netflix/servo/publish/apache/ApacheStatusPoller.java
servo-apache/src/test/java/com/netflix/servo/publish/apache/ApacheStatusPollerTest.java

Change the apache status parsing to only generate a set of whitelisted metrics.

Deal with new apache status output

---

servo-core/src/main/java/com/netflix/servo/monitor/BasicTimer.java
servo-core/src/main/java/com/netflix/servo/monitor/DoubleCounter.java
servo-core/src/test/java/com/netflix/servo/monitor/BasicTimerTest.java
servo-core/src/test/java/com/netflix/servo/monitor/DoubleCounterTest.java

The 'min' gauge in a BasicTimer has not proven useful in practice. Timers that don't get updated will report 0, which makes the aggregate value of dubious value.
This PR replaces the min gauge with a totalOfSquares counter that can be used to accurately compute the standard deviation of samples recorded.

totalOfSquares replaces minGauge in BasicTimer

---

servo-aws/src/main/java/com/netflix/servo/publish/cloudwatch/CloudWatchMetricObserver.java

CloudWatch has a max 20 metrics per request limit. This fixes servo publishing
all metrics above the 20 limit without batching.

Fix silent failure publishing to CloudWatch.

---

build.gradle
servo-aws/build.gradle

Guava verions set to 18 to match the current version used
by platform internally.

update guava and aws sdk

---

servo-atlas/build.gradle

Update rxhttp version to fix NoSuchMethodError due
to reference to Spectator.config. Also fixes the
cleanup setting to work as expected with the injected
config.

iep-rxhttp:0.3.2

---

servo-core/src/main/java/com/netflix/servo/jmx/JmxMonitorRegistry.java
servo-graphite/src/test/java/com/netflix/servo/publish/graphite/GraphiteMetricObserverTest.java

When profiling an application that registers objects in parallel the synchronization caused the operations to block. Refactored the synchronization block to lock on the ObjectName instead of the MBeanServer.

Refactor synchronized block on JmxMonitorRegistry

---

servo-core/src/main/java/com/netflix/servo/publish/NormalizationTransform.java

Current behavior is to drop the metric completely if we cannot understand the 'type' tag. With this change we just leave the metric untouched.

Handle unknown type tag values

---

servo-aws/src/main/java/com/netflix/servo/publish/cloudwatch/CloudWatchMetricObserver.java

This should let us catch errors such as NoSuchMethodError if/when AWS makes an incompatible API change

Add counters for Errors to CloudWatchMetricObserver

---

servo-apache/src/main/java/com/netflix/servo/publish/apache/ApacheStatusPoller.java
servo-apache/src/test/java/com/netflix/servo/publish/apache/ApacheStatusPollerTest.java

This change removes: "ReqPerSec", "BytesPerSec",
and "BytesPerReq". These metrics are averaged over
the life of the process and create a confusion
when compared to other sources of RPS like the
"Total_Accesses" counter or the count statistic
on the log parsing timer.

remove confusing apache stats

---

servo-atlas/src/main/java/com/netflix/servo/publish/atlas/AtlasMetric.java
servo-atlas/src/main/java/com/netflix/servo/publish/atlas/UpdateRequest.java
servo-atlas/src/main/java/com/netflix/servo/publish/atlas/ValidCharacters.java
servo-atlas/src/test/java/com/netflix/servo/publish/atlas/ValidCharactersTest.java

Allows '^' and '~' as values for nf.asg and nf.cluster, but still
rejects them for other tags.

Relax Atlas Validation rules for some group tags

---

servo-core/src/main/java/com/netflix/servo/publish/FileMetricObserver.java

The default date format for file metrics observer was using
year-day-month, which is quite unintuitive. This updates the default
format to year-month-day.

Use year-month-day by default in file names

---

servo-aws/src/main/java/com/netflix/servo/publish/cloudwatch/CloudWatchMetricObserver.java

Logs AmazonServiceException just like other exceptions
when publishing cloudwatch data. Helps make debugging
easier if the publish is failing due to bad or expired
credentials.

fix #410, log AmazonServiceException

---

servo-core/src/main/java/com/netflix/servo/stats/StatsBuffer.java
servo-core/src/test/java/com/netflix/servo/stats/StatsBufferTest.java

In my opinion the current variance (and by consequence the standard deviation) computation is imprecise, when curSize is not high (when curSize < 10 for example):
```java
variance = (sumSquares / curSize) - (mean * mean);
```
The computation I suggest in this pull request does not hurt and is precise:
```java
if (curSize == 1) {
variance = 0d;
} else {
variance = (sumSquares - ((double) total * total / curSize)) / (curSize - 1);
}
```
For reference:
http://web.archive.org/web/20050512031826/http://helios.bto.ed.ac.uk/bto/statistics/tress3.html

variance and standard deviation are imprecise when size is not high

---

servo-graphite/src/test/java/com/netflix/servo/publish/graphite/GraphiteMetricObserverTest.java

In many cases the ip used before would not allow access
in causing the connections to timeout.

use localhost explicitly for graphite test

---

build.gradle

With the pmd version 5.5.4 we're now getting:
```
Exception applying rule InvalidSlf4jMessageFormat on file servo/servo-core/src/main/java/com/netflix/servo/DefaultMonitorRegistry.java, continuing with next rule
java.lang.NullPointerException
```

Upgrade pmd to 5.6.1 to avoid NPE

---

servo-atlas/src/main/java/com/netflix/servo/publish/atlas/AtlasMetricObserver.java
servo-atlas/src/main/java/com/netflix/servo/publish/atlas/AtlasPrettyPrinter.java
servo-atlas/src/test/java/com/netflix/servo/publish/atlas/AtlasPrettyPrinterTest.java

Add hooks to be able to dump the JSON payload sent to atlas backends.
This is a bit more useful to debug certain use cases than
`FileMetricsObserver`

Hooks to dump the JSON payload sent to atlas

---

OSSMETADATA
README.md

We have mentioned this several times in issues that
come up, but it isn't necessarily easy for someone
to find. This change adds a prominent notice about
the current status to the top of the main readme.

clarify project status

---

servo-core/src/main/java/com/netflix/servo/publish/MonitorRegistryMetricPoller.java

Count the number of times we triggered a timeout exception getting the
value of a monitor.

Add timeout exception counter to the registry

---

.travis.yml

It was `BINTRAY_PUBLISH` in the travis config but the
script is checking `GRADLE_PUBLISH`.
Fixes #439

fix name of publish env variable

---

servo-core/src/main/java/com/netflix/servo/monitor/DynamicGauge.java

Similar to a `DynamicCounter`. Mostly for backwards compatibility with
some old applications. Its usage can be surprising so it's not
recommended for general usage.

Dynamic gauge that auto-expires

---

servo-apache/build.gradle
servo-atlas/build.gradle
servo-aws/build.gradle
servo-core/build.gradle
servo-example/build.gradle
servo-graphite/build.gradle
servo-tomcat/build.gradle

Should help avoid compatibility problems in the future
if users try to pull these in before we support a proper
`module-info.java`. For more details see:
http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html

add Automatic-Module-Name to manifest

---

servo-aws/src/main/java/com/netflix/servo/tag/aws/AwsInjectableTag.java
servo-core/src/main/java/com/netflix/servo/DefaultMonitorRegistry.java

Most of the secured applications are not given access to all system properties on server. Making this change to prevent reading all the system properties and just read the properties that are required for creating DefaultMonitorRegistry instance.

getting indiv props instead of reading all props

---

build.gradle
codequality/pmd.xml
servo-apache/src/main/java/com/netflix/servo/publish/apache/ApacheStatusPoller.java
servo-aws/src/main/java/com/netflix/servo/publish/cloudwatch/CloudWatchMetricObserver.java
servo-aws/src/main/java/com/netflix/servo/tag/aws/AwsInjectableTag.java
servo-core/src/main/java/com/netflix/servo/util/Reflection.java
servo-example/src/main/java/com/netflix/servo/example/BaseHandler.java
servo-example/src/main/java/com/netflix/servo/example/EchoHandler.java
servo-example/src/main/java/com/netflix/servo/example/ExitHandler.java

Using version 6.3.0 fixes the NPE issue, but had other warnings enabled
that were breaking the build. Remove the `ClassNamingConvention` rule
which was forcing us to append `Util` to some publicly exposed classes.

Update PMD to fix InvalidSlf4jMessageFormat: NPE

---

build.gradle
servo-core/src/main/java/com/netflix/servo/SpectatorContext.java

Servo gauges were sampled by default once a minute, and the default
spectator polling frequency is 5s. That could cause a noticeable
increase in CPU usage attributed to monitoring. This change makes
spectator sample the values every 59s.

Poll gauge values less frequently

---

servo-core/src/main/java/com/netflix/servo/monitor/StatsMonitor.java
servo-core/src/test/java/com/netflix/servo/monitor/StatsMonitorTest.java

Before it was using calls to `getMonitors` to update the
last used time. That method will not get called when
delegating to Spectator and thus it will always expire
15 minutes after registration and never come back.
This changes the last used time to get updated when
values are recorded rather than when they are read using
`getMonitors`.

base StatsMonitor expiration on writes

---

servo-core/src/main/java/com/netflix/servo/SpectatorContext.java

Adds a warning level log message if the registry used with
the SpectatorContext is overwritten. This should help with
debugging cases where Servo metrics are not being reported
properly because of initialization bugs in the application.

warn if SpectatorContext registry is overwritten

---

servo-core/src/main/java/com/netflix/servo/util/Preconditions.java

and the allocation overhead of creating a string array
during application profiling found that some allocation can be avoided if we explicitly invoke the checkArgument method without varargs
Allocation profiling via async-profiler:
```
--- 1451114625215846968 bytes (21.40%), 10371 samples
[ 0] java.lang.String[]
[ 1] com.netflix.servo.tag.BasicTag.checkNotEmpty
[ 2] com.netflix.servo.tag.BasicTag.<init>
[ 3] com.netflix.servo.tag.Tags.newTag
[ 4] com.netflix.servo.monitor.MonitorConfig$Builder.withTag
```

add a checkArgument that avoids varargs 

---

servo-core/src/main/java/com/netflix/servo/DefaultMonitorRegistry.java
servo-core/src/main/java/com/netflix/servo/NoopMonitorRegistry.java
servo-core/src/test/java/com/netflix/servo/DefaultMonitorRegistryTest.java
servo-core/src/test/java/com/netflix/servo/monitor/MonitorsTest.java

Internally Servo is deprecated and delegates to Spectator.
This change would reduce the overhead for things that are
still using the Servo APIs. The main benefit is that the
data would no longer be exported to JMX.
Note, this could be quite disruptive to anyone else using
Servo. Since it is all setup via sytem properties, there
isn't a convenient way to only change the default we use
internally.
After making this change, I noticed that loading the JMX
monitor registry explicitly using the property no longer
worked. That has been fixed so the old behavior can be
acheived using a system property.

switch to no op monitor registry by default

---

README.md

Adds a prominent notice about no-op behavior to the readme
as discussed in #466.

add notice about noop behavior

---

.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml

Starting February 1st, 2025, Github is closing down v1-v2 of actions/cache (read more about it in this [changelog announcement](https://app.github.media/e/er?s=88570519&lid=6815&elqTrackId=08a5e2ee0de44b669cfee44c72a218f2&elq=553eec1a7c454e1f86dace7dd5ce9583&elqaid=4282&elqat=1&elqak=8AF5E7AAA12E3C7C230E5849DC6FF5707A505F45E589E4FD0E873A034D6DD7B23D08)) as well as all previous versions of the @actions/cache package in actions/toolkit. Attempting to use a version of the @actions/cache package or actions/cache after the announced deprecation date will result in a workflow failure. If you are pinned to a specific version or SHA of the cache action, your workflows will also fail after February 1st.
Use this link to re-run the recipe: …

refactor: Change GitHub Action version to address deprecation of v1/v2
